doctor/urls.py
from django.urls import path
from . import views
app_name = "doctor"
urlpatterns = [
path('doctor-dashboard/', views.doctor_dashboard, name='doctor-dashboard'),
path('all-patients/', views.all_patients, name='all-patients'),
path('new-appointment/', views.new_appointment, name='new-appointment'),
path('appointment-detail/<int:id>/', views.appointment_detail, name='appointment-detail'),
path('create-invoice/', views.create_invoice, name='create-invoice'),
path('patient-settings/<int:id>/', views.patient_settings, name='patient-settings'),
path('billing-list/', views.billing, name='billing-list'),
path('invoice-detail/<int:id>/', views.invoice_detail, name='invoice_detail'),
path('download-pdf/<int:id>/', views.pdf_download, name='pdf_download'),
path('doctor-settings/<int:id>/', views.doctor_settings, name='doctor-settings'),
path('user-history/<int:id>/', views.UserHistory, name='user_history'),
path('doc-user-history/<int:id>/<int:code>/', views.user_history_detail, name='user_history_detail'),
path('searchpatient/', views.search1, name='searchpatient'),

]

doctor/templates/all-patients.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
        <!-- start section content -->
        <div class="content-body">
            <div class="warper container-fluid">
                <div class="all-patients main_container">
                    <div class="row page-titles mx-0">
                        <div class="col-sm-6 p-md-0">
                            <div class="welcome-text">
                            </div>
                        </div>
                        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="breadcrumb-item active"><a href="new-patient.html">All Patients</a></li>
                            </ol>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header fix-card">
                                    <div class="row">
                                        <div class="col-8">
                                            <h4 class="card-title"> All Patients </h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        {% comment %} <table id="example2" class="display nowrap">
                                            <thead>
                                                <tr>
                                                    <th>S.N</th>
                                                    <th>Full Name</th>
                                                    <th>Email</th>
                                                    <th>Mobile No.</th>
                                                    <th>Sex</th>
                                                    <th>Blood Group</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for li in patients %}
                                                <tr>
                                                    <td>{{forloop.counter}}</td>
                                                    <td>{{li.first_name}}</td>
                                                    <td>{{li.email}}</td> 
                                                    <td>{{li.mobile}}</td>
                                                    <td>what</td>
                                                    <td>{{li.blood_group}}</td>
                                                    
                                                   
                                                </tr>
                                                {% endfor %}
                                                
                                               
                                            </tbody>
                                        </table> {% endcomment %}
                                        <table id="example1" class="display nowrap">
                                            <thead>
                                                <tr>
                                                    <th>S.N</th>
                                                    <th>Full Name</th>
                                                    <th>Email</th>
                                                    <th>Mobile No.</th>
                                                    <th>Sex</th>
                                                    <th>Blood Group</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for li in patients %}
                                                <tr>
                                                    <td> {{forloop.counter}} </td>
                                                    <td> {{li}} </td>
                                                    <td>{{li.email|default_if_none:"N/A"}}</td>
                                                    <td> {{li.mobile|default_if_none:"N/A"}} </td>
                                                    <td> {{li.sex|default_if_none:"N/A"}} </td>
                                                    <td>{{li.blood_group|default_if_none:"N/A"}}</td>
                                                    <td>
                                                    <a class='mr-4 vue'>
                                                        <a href="{% url 'doctor:patient-settings' li.id %}"><span class='fa fa-eye' aria-hidden='true'></span></a>
                                                    </a>
                                                    </td>
                                                </tr>
                                                {% endfor %}
                                           
                                              
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        ...
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End section content -->


    <!-- Show data patient -->
    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
        <!-- <div > -->
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel"><img class="rounded-circle" width="35" src="assets/images/patients/user1.jpg" alt=""> Tiger Nixon </h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="insertHere"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- End Show data patient -->


{% endblock %}

doctor/templates/appointment_detail.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-body">
    <div class="warper container-fluid">
        <div class="doctorino_settings main_container">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                </div>
            </div>
            {% if messages %} {% for message in messages%}
            <div class="mt-3 alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
              <strong></strong> {{message}}
              {% comment %} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button> {% endcomment %}
            </div>
            {% endfor %} {% endif %}
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <h4 class="card-title"> Appointment By <a href="{% url 'Management_system:patient-settings' appointment.patient.id  %}">{{appointment.patient}}</a> </h4>
                            <div class="float-right">
                                <!-- Button trigger modal -->
                               <div class="d-flex align-items-center justify-content-center">
                                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">
                                    Create Invoice For this Appointment
                                </button>
                                
                                <!-- Modal -->
                               
                                <form method="POST" class="mx-1">
                                    {% csrf_token %}
                                    {% if appointment.status == "Pending" %}
                                    <input type="submit" name="start_appointment" class="btn btn-primary" value="Start Appointment">
                                    {% elif appointment.status == "In Progress" %}
                                    <input type="submit" name="deliver_appointment" class="btn btn-primary" value="Deliver Appointment">
                                    {% endif %}
                                </form>
                               </div>
                            </div>
                        </div>
                        
                        <div class="card-body">
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Create Invoice</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="" method="post">
                                            {% csrf_token %}
                                    {{invoice_form|crispy}}
                                    
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <input type="submit" name="create_invoice" class="btn btn-primary" value="Create Invoice" />
                                </form>
                                </div>
                                </div>
                                </div>
                            </div>
                            <p>   <strong>Appointment Status : </strong>{{appointment.status}}</p>
                            <p><strong>Paid Status :</strong> {% if appointment.paid %}Paid {% else %}Not Paid Yet{% endif %}</p>
                            {% if appointment.paid %}
                            <p><strong>Paid Receipt : </strong>
                           <a target="blank" href=" {{appointment.receipt_url}}"> {{appointment.receipt_url}}</a>
                            </p>
                           {% endif %}
                            <form method="POST" >
                               {% csrf_token %}
                                <div class="row">
                                   <form method="post">
                                    <div class="col-xl-6">
                                       
                                        <div id="form_date" data-doctorid="{{doctor.id}}" data-url="{% url 'Management_system:weekday_time_info' %}" class="form-group row">
                                     
                                            {{app_form.appointment_date|as_crispy_field}}

                                            {% comment %} <input type="text" class="form-control" value="{{appointment.appointment_date }}"> {% endcomment %}
                                            
                                        </div>
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                         
                                            {{app_form.description|as_crispy_field}}

                                           {% comment %} <input type="text" class="form-control mx-2" value="{{appointment.description }}"/> {% endcomment %}
                                        </div>
                                    </div>
                                   
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                     
                                            {{app_form.appointment_time|as_crispy_field}}
                                            {% comment %} <input type="text" class="form-control" value="{{appointment.appointment_time }}"/> {% endcomment %}

                                           
                                        </div>
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                      
                                       
                                            {{app_form.appointment_time_end|as_crispy_field}}
                                            {% comment %} <input type="text" class="form-control mx-2" value="{{appointment.appointment_time_end }}"/> {% endcomment %}
 
                                        </div>
                                    </div>
                                    <input class="btn btn-secondary mt-3 w-auto float-right" type="submit" value="Update Appointment" name="update_app">

                                </form>
                                    <hr>
                                    <a href="{% url 'doctor:user_history' appointment.patient.id%}" class="mt-3 btn btn-primary w-auto">
                                        Patient's Medical History
                                    </a>
                                    {% comment %} <h5>See Patient's Medical History</h5> {% endcomment %}
                                    <hr>
                                    {% if appointment.status != "Pending" %}
                                    <h5 >Add Report </h5>

                                    <div class="m-3">
                                        <form action="" method="post">
                                            {% csrf_token %}    
                                            {{form|crispy}}
                                            <input type="submit" name="create_report" class="btn btn-primary" value="Create Report">
                                        </form>
                                    </div>
                                    {% endif %}

                                    

                                
                                </div>
                               
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End section content -->

{% endblock %}  
{% block js %}
<style>
    .btn-primary{
        background:#7366FF !important;
        border:0 !important;
    }
    .form-control{
        padding:29px !important;
        margin-right: 10px !important;
    }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" 
integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock js %}

doctor/templates/create-invoice.html
{% extends 'index.html' %} {% load static %} {% load crispy_forms_tags %} 
{% block content %}

<!-- start section content -->
<div class="content-body">
  <div class="warper container-fluid">
    <div class="create_invoice main_container">
      <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
          <div class="welcome-text">
            <h4 class="text-primary">Create-invoice</h4>
          </div>
        </div>
        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">
              <a href="/create-invoice.html">create-invoice</a>
            </li>
          </ol>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="card shadow mb-4">
            <div class="card-header">
              <h4 class="card-title">create invoice</h4>
            </div>
            <div class="card-body">
              {% if messages %} {% for message in messages%}
              <div
                class="mt-3 alert alert-danger alert-dismissible fade show"
                role="alert"
              >
                <strong></strong> {{message}}
              </div>
              {% endfor %} {% endif %}
              <form action="{% url 'doctor:create-invoice' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                  <div class="col-lg-4 col-sm-6">
                    <div class="form-group">
                      {{form.patient|as_crispy_field}}
                    </div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                    <div class="form-group">
                      {{form.payment_mode|as_crispy_field}}
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-group">
                      {{form.payment_stats|as_crispy_field}}
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-4 col-sm-6">
                    <div class="form-group">{{form.title|as_crispy_field}}</div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend"></div>
                        {{form.price|as_crispy_field}}
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-sm-6">
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary w-100 h-56">
                        Create Invoice
                      </button>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End section content -->

{% endblock %}

doctor/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Health Care Platform{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" href="{% static 'assets/images/favicon-32x32.png' %}">

    <!-- Base Styling  -->
   
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
    <link rel="stylesheet type="text/css" href="https://jeremyfagis.github.io/dropify/dist/css/dropify.min.css"/>
</head>

<body>
    <div id="main-wrapper" class="show">


        <!-- start logo components -->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'accounts:login' %}"><img class="brand-title" src="{% static 'images/Grace101.png' %}" alt=""></a>
            </div>
        </div>
        <!-- End logo components -->

        
         <!-- start section sidebar -->
         <aside class="left-panel nicescroll-box">
            <nav class="navigation">
                <ul class="list-unstyled main-menu">
                    <li class="has-submenu active">
                        <a href="{% url 'doctor:doctor-dashboard' %}">
                            <i class="fas fa-th-large"></i>
                            <span class="nav-label">Dashboard</span>
                        </a>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-users"></i>
                            <span class="nav-label">Patients</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'doctor:all-patients' %}">All Patients</a></li>
                        </ul>
                    </li>
                    <li class="has-submenu">
                        <a href="{% url 'doctor:new-appointment' %}">
                            <i class="fas fa-calendar-plus"></i>
                            <span class="nav-label">Appointment</span>
                        </a>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-file-invoice"></i>
                            <span class="nav-label">Billing</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'doctor:create-invoice'%}">Create Invoice</a></li>
                            <li><a href="{% url 'doctor:billing-list' %}">Billing List</a></li>
                        </ul>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-cog"></i>
                            <span class="nav-label">Settings</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'doctor:doctor-settings' request.user.id %}">Doctor Settings</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </aside>
        <!-- End section sidebar -->

        <!-- start section header -->
        <div class="header">
            <header class="top-head container-fluid">
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="line"></span><span class="line"></span><span class="line"></span>
                    </div>
                </div>
                <div class="header-right">
                    <form method="get" action="{% url 'doctor:searchpatient' %}" id="search-form">
                        <div class="input-group rounded">
                            <input type="search" name="search1" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" style="height: 34px;" />
                            <span class="input-group-text border-0" id="search-addon">
                              <i class="fas fa-search "></i>
                            </span>
                        </div>
                    </form>
                    <div class="my-account-wrapper">
                        <div class="account-wrapper">
                            <div class="account-control">
                                <a class="login header-profile" href="#" title="Sign in">
                                    <div class="header-info">
                                        <span>{{request.user.first_name}}</span>
                                    </div>
                                    {% if request.user.profile_pic %}
    <img src="{{request.user.get_image}}" style="object-fit:cover" alt="people">
{% else %}
    <div style="background:#333;color:white;padding:4px;width:30px;border-radius:50%;display:grid;place-items:center;">{{request.user.first_name.0|title}}</div>
{% endif %}
                           </a>
                                <div class="account-dropdown-form dropdown-container">
                                    <div class="form-content">
                                        {% if request.user.is_patient %}
                                        <a href="{% url 'Management_system:patient-settings' request.user.id %}">
                                            <i class="far fa-user"></i>
                                            <span class="ml-2">Profile</span>
                                        </a>
                                     {% elif request.user.is_doctor %}
                                        <a href="{% url 'doctor:doctor-settings' request.user.id %}">
                                            <i class="far fa-user"></i>
                                            <span class="ml-2">Profile</span>
                                        </a>
                                        {% endif %}
                                        <a href="{% url 'accounts:logout' %}">
                                            <i class="fas fa-sign-in-alt"></i>
                                            <span class="ml-2">Logout </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>


                {% block content %}
                {% endblock %}

        <div class="footer">
            <div class="copyright">
                <p class="mb-0"> <a href="uxign.com" target="_blank">Health Care Platform</a> 2024
                </p>
            </div>
        </div>
    </div>

    
    <!-- JQuery v3.5.1 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- popper js -->
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>

    <!-- Date Range Picker -->
    <script src="{% static 'plugins/daterangepicker/daterangepicker.min.js' %}"></script>
    {% comment %} <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script> {% endcomment %}

    <!-- Datatable -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/init-tdatatable.js' %}"></script>

    <!-- Chart js -->
    <script src="{% static 'plugins/chart/chart/Chart.min.js' %}"></script>
    <script src="{% static 'js/charts-custom.js' %}"></script>

    <!-- Main Custom JQuery -->
    <script src="{% static 'js/toggleFullScreen.js' %}"></script>
    <script
  type="text/javascript"
  src="https://jeremyfagis.github.io/dropify/dist/js/dropify.min.js"
></script>
<script src="{% static 'js/doc_settings.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  
    {% block js %}{% endblock js %}

</body>
</html>