accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
 path('', views.login, name='login'),
 path('logout/', views.logout, name='logout'),
 path('register/', views.register, name='register'),
 path('doctor-register/', views.doctor_register, name='doctor-register'),
 path('forget-password/', views.forget_password, name='forget-password'),
  path('choose_usertype/', views.choose_usertype, name='choose_usertype'),

path('password_reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name='password_reset_confirm'),
path('password-reset-complete',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),


]

accounts/templates/accounts/Login.html
{% load socialaccount %}
{% load static %} 
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
      {% block title %}Health Care Platform{% endblock %}
    </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png" /> 
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'main/css/custom.css' %}" rel="stylesheet" />

  </head>
  {% block content %}
  <body>
    <div id="main-wrapper" class="show">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xl-7 p-0 b-center bg-size">
            <img
              class="img-fluid"
              src="{%static 'images/bg-register.jpg' %}"
              alt="Grace app"
            />
          </div>
          <div class="col-xl-5 p-0">
            <div class="login-tabib">
              <div>
                <div class="text-center">
                  <a class="logo" href="index.html">
                    <img
                      class="img-fluid"
                      src="{% static 'images/Grace101.png' %}"
                      alt="login page"
                    />
                  </a>
                </div>
                <div class="login-main">
                  <form
                    class="theme-form"
                    action="{% url 'accounts:login' %}"
                    method="POST">
                   
                    <h4>Sign in to account</h4>
                    <p>Enter your email & password to login</p>
                    {% if messages %} {% for message in messages%}
                    <div class="mt-3 alert alert-primary alert-dismissible fade show" role="alert">
                      <strong></strong> {{message}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    {% endfor %} {% endif %}
                    {% csrf_token %}
                    <div class="form-group m-b-10">
                      <label class="col-form-label">Email Address</label>
                      <input
                        class="form-control"
                        type="email"
                        name="email"
                        placeholder="Enter your Email here"
                      />
                    </div>
                    <div class="form-group m-b-10">
                      <label class="col-form-label">Password</label>
                      <div class="form-input position-relative">
                        <input
                          class="form-control"
                          type="password"
                          name="password"
                          placeholder="*********"
                        />
                        <div class="show-hide"><span class="show"></span></div>
                      </div>
                    </div>
                    <div class="form-group mb-0">
                      <div class="p-0 checkbox">
                        <input type="checkbox" name="remember_me" id="rem"/>
                        <label class="text-muted" for="rem"
                          >Remember Me</label
                        >
                      </div>
                      <a
                        class="link text-primary"
                        href="{% url 'accounts:forget-password' %}"
                        >Forgot password?</a
                      >
                      <div class="mt-3">
                        <button
                          type="submit"
                          href="{% url 'accounts:login' %}"
                          class="btn btn-primary w-100"
                        >
                          sign in
                        </button>
                      </div>
                    </div>

                    <p class="mt-4 mb-3" style="text-align: center">
                      Don't have account?<a
                        class="ms-2 text-primary text-center"
                        href="{% url 'accounts:register' %}"
                        >Create Account</a
                      >
                    </p>
                    <div class="row">
                      <div class="col-12" style="text-align: center">
                        <a
                        class="btn btn-outline-dark"
                        href="{% provider_login_url 'google' %}"
                        role="button"
                        style="text-transform: none"
                        ></a>
                      
                          <img
                            width="20px"
                            style="margin-bottom: 1px; margin-right: 10px"
                            alt="Google sign-in"
                            src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"
                          />
                          Login with Google
                        </a>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- JQuery v3.5.1 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- popper js -->
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>

    <!-- Date Range Picker -->
    <script src="{% static 'plugins/daterangepicker/daterangepicker.min.js' %}"></script>

    <!-- Main Custom JQuery -->
    <script src="{% static 'js/toggleFullScreen.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Minified CSS and JS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>


    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/choose_usertype.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Health Care Platform{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>
<body>
    <div id="main-wrapper" class="show">

        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="{% static 'images/Grace101.png' %}" alt="loogin page">
                    </a>
                </div>
                <div class="login-main">
                    {% if messages %} {% for message in messages%}
                    <div class="mt-3 alert alert-danger alert-dismissible fade show" role="alert">
                      <strong></strong> {{message}}
                      
                    </div>
                    {% endfor %} {% endif %}
                    <form id="updateform" class="theme-form" action="" method="POST">
                        {% csrf_token %}
                        <h4>Add User Role </h4>
                        <div class="form-group m-b-10">
                            <p>Hello ,<strong> {{request.user }}</strong> Please Enter what you want to sign up with
                            <div  class="form-input position-relative">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="usertypeoptions"  id="inlineRadio1" value="doctor">
                                    <label class="form-check-label" for="inlineRadio1">Doctor</label>
                                  </div>
                                  <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="usertypeoptions" id="inlineRadio2" value="patient">
                                    <label class="form-check-label" for="inlineRadio2">Patient</label>
                                  </div>
                                 <div id="lice" class="">
                                    <label >License Number :</label>
                                    <input id="licenseid" name="license" placeholder ="NPXXXXXXXX" type="text" class="mt-2 form-control">
                                 </div>
                                 <div class="form-group mb-0">
                                    <div class="mt-3">
                                        <button onclick="updateinfo()" type="submit" class="btn btn-primary w-100">Update Info</button>
                                    </div>
                                </div>
                            </div>
                        </div>
             
                        </p>
                    </form>
                </div>
            </div>
        </div>

    </div>

   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    $("#lice").hide()
    var radioval=null;
    var lice_len =$("#licenseid").val()
    function updateinfo(){
        if(radioval==null){
            alert("please check at least one role !")
        }
      
        else{
           return $("#updateform").submit()
        }
    }

    $('input[type=radio][name=usertypeoptions]').change(function() {
        radioval=this.value
        if (this.value == 'doctor') {

            $("#lice").show()
        }
        else{
            $("#lice").hide()
        }
       
    });
</script>
</body>

</html>

accounts/templates/accounts/doctor-register.html
{% load static %}{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Health Care Platform{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>
{% block content %}
<body>
    <div id="main-wrapper" class="show">

        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-7 p-0 b-center bg-size">
                    <img class="img-fluid" src="{% static 'images/bg-register.jpg' %}" alt="tabib app">
                </div>
                <div class="col-xl-5 p-0">
                    <div class="login-tabib">
                        <div>
                            <div class="text-center">
                                <a class="logo" href="index.html">
                                    <img class="img-fluid" src="{%static 'images/Grace1.png' %}" alt="loogin page">
                                </a>
                            </div>
                            <div class="login-main">
                                <form class="theme-form" action="{% url 'accounts:doctor-register' %}" method="POST">
                                    {% csrf_token %}
                                    <h4>Create your account</h4>
                                    <p>Enter your personal details to create account</p>
                                    {% if messages %} {% for message in messages%}
                                    <div class="mt-3 alert alert-danger alert-dismissible fade show" role="alert">
                                      <strong></strong> {{message}}
                                     
                                    </div>
                                    {% endfor %} {% endif %}
                                    <div class="form-group m-b-10">
                                        <label class="col-form-label pt-0">Your Name</label>
                                        <div class="row g-2">
                                            <div class="col-md-12 col-lg-6">
                                                <div class="form-group mb-0">
                                                    {{form.first_name|as_crispy_field}}
                                                </div>
                                            </div>
                                            <div class="col-md-12 col-lg-6">
                                                <div class="form-group mb-0">
                                                   {{form.last_name|as_crispy_field}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group m-b-10">
                                        <label class="col-form-label">Email Address</label>
                                        {{form.email|as_crispy_field}}
                                    </div>
                                    <div class="form-group m-b-10">
                                        <label class="col-form-label">Password</label>
                                        <div class="form-input position-relative">
                                            {{form.password1|as_crispy_field}}
                                        </div>
                                    </div>
                                    <div class="form-group m-b-10">
                                        <label class="col-form-label">Confirm Password</label>
                                        <div class="form-input position-relative">
                                            {{form.password2|as_crispy_field}}
                                            <div class="show-hide"><span class="show"></span></div>
                                        </div>
                                    </div>
                                    <div class="form-group m-b-10">
                                        <label class="col-form-label">License Number</label>
                                       <input placeholder="NPXXXXXXXX" name="license_number" type="text" class="form-control">
                                    </div>
                                    <div class="form-group mb-0">
                                        <div class="checkbox p-0">
                                            {{form.term}}
                                            <label class="text-muted" for="term_cond">Agree with<a
                                       class="ms-2 text-primary" href="#">Privacy Policy</a></label>
                                        </div>
                              
                                        <button type="submit" class="btn btn-primary w-100" > Register </button>
                                    </div>
                                    <p class="mt-4 mb-0">Already have an account?<a class="ms-2 text-primary" href="{% url 'accounts:login' %}">Sign in</a>
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- JQuery v3.5.1 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- popper js -->
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>

    <!-- Date Range Picker -->
    <script src="{% static 'plugins/daterangepicker/daterangepicker.min.js' %}"></script>

    <!-- Main Custom JQuery -->
    <script src="{% static 'js/toggleFullScreen.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock %}

</body>

</html>

accounts/templates/accounts/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Health Care Platform{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>
{% block content %}
<body>
    <div id="main-wrapper" class="show">

        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="{% static 'images/Grace1.png' %}" alt="loogin page">
                    </a>
                </div>
                <div class="login-main">
                    {% if messages %} {% for message in messages%}
                    <div class="mt-3 alert alert-danger alert-dismissible fade show" role="alert">
                      <strong></strong> {{message}}
                      
                    </div>
                    {% endfor %} {% endif %}
                    <form class="theme-form" action="{% url 'accounts:forget-password' %}" method="POST">
                        {% csrf_token %}
                        <h4>Recover my password </h4>
                        <div class="form-group m-b-10">
                            <p>Please enter your email address below to receive instructions for resetting password.</p>
                            <div class="form-input position-relative">
                                <input class="form-control" name="email" type="email" placeholder="Enter your email">
                                <div class="show-hide"><span class="show"></span></div>
                            </div>
                        </div>
                        <div class="form-group mb-0">
                            <div class="mt-3">
                                <button type="submit" class="btn btn-primary w-100">Reset password</button>
                            </div>
                        </div>
                        <p class="mt-4 mb-0">Know your password?<a class="ms-2 text-primary text-center" href="{% url 'accounts:login'%}">Sign in</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- JQuery v3.5.1 -->
    <script src="assets/plugins/jquery/jquery.min.js"></script>

    <!-- popper js -->
    <script src="assets/plugins/popper/popper.min.js"></script>

    <!-- Bootstrap -->
    <script src="assets/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Moment -->
    <script src="assets/plugins/moment/moment.min.js"></script>

    <!-- Date Range Picker -->
    <script src="assets/plugins/daterangepicker/daterangepicker.min.js"></script>

    <!-- Main Custom JQuery -->
    <script src="assets/js/toggleFullScreen.js"></script>
    <script src="assets/js/main.js"></script>

{% endblock %}

</body>

</html>

accounts/templates/accounts/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Health Care Platform{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>
{% block content %}
<body>
    <div id="main-wrapper" class="show">

        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="{% static 'images/Grace1.png' %}" alt="loogin page">
                    </a>
                </div>
                <div class="login-main">
                    <form class="theme-form" action="{% url 'accounts:password_reset_done' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group m-b-10">
                            <p>Youe password has been set.</p>
                        </div>
                        <div class="form-group mb-0">
                            <div class="mt-3">
                                <a href="{% url 'accounts:login' %}" class="btn btn-primary w-100">Sign in</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- JQuery v3.5.1 -->
    <script src="assets/plugins/jquery/jquery.min.js"></script>

    <!-- popper js -->
    <script src="assets/plugins/popper/popper.min.js"></script>

    <!-- Bootstrap -->
    <script src="assets/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Moment -->
    <script src="assets/plugins/moment/moment.min.js"></script>

    <!-- Date Range Picker -->
    <script src="assets/plugins/daterangepicker/daterangepicker.min.js"></script>

    <!-- Main Custom JQuery -->
    <script src="assets/js/toggleFullScreen.js"></script>
    <script src="assets/js/main.js"></script>

{% endblock %}

</body>

</html>

accounts/templates/accounts/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Health Care Platform{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>
{% block content %}
<body>
    <div id="main-wrapper" class="show">

        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="{% static 'images/Grace1.png' %}" alt="loogin page">
                    </a>
                </div>
                <div class="login-main">
                    <form class="theme-form" action="{% url 'accounts:password_reset_done' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group m-b-10">
                            <p>An email has been sent with instructions to reset your password.</p>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- JQuery v3.5.1 -->
    <script src="assets/plugins/jquery/jquery.min.js"></script>

    <!-- popper js -->
    <script src="assets/plugins/popper/popper.min.js"></script>

    <!-- Bootstrap -->
    <script src="assets/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Moment -->
    <script src="assets/plugins/moment/moment.min.js"></script>

    <!-- Date Range Picker -->
    <script src="assets/plugins/daterangepicker/daterangepicker.min.js"></script>

    <!-- Main Custom JQuery -->
    <script src="assets/js/toggleFullScreen.js"></script>
    <script src="assets/js/main.js"></script>

{% endblock %}

</body>

</html>

accounts/templates/accounts/patient-register.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
      {% block title %}Health Care Platform{% endblock %}
    </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png" />
    <!-- Base Styling  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet" />
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet" />
  </head>
  {% block content %}
  <body>
    <div id="main-wrapper" class="show">
      <div class="login-tabib">
        <div>
          <div class="text-center">
            <a class="logo" href="index.html">
              <img
                class="img-fluid"
                src="{%static 'images/Grace1.png' %}"
                alt="loogin page"
              />
            </a>
          </div>
          <div class="login-main">
            <form
              class="theme-form"
              action="{% url 'accounts:register' %}"
              method="POST"
            >
              {% csrf_token %}
              <h4>Create your account</h4>
              <p>Enter your personal details to create a patient account</p>
    
              <div class="form-group m-b-10">
                <label class="col-form-label pt-0">Your Name</label>
                <div class="row g-2">
                  <div class="col-md-12 col-lg-6">
                    <div class="form-group mb-0">{{form.first_name|as_crispy_field }}</div>
                  </div>
                  <div class="col-md-12 col-lg-6">
                    <div class="form-group mb-0">{{form.last_name|as_crispy_field }}</div>
                  </div>
                </div>
              </div>
              <div class="form-group m-b-10">
                <label class="col-form-label">Email Address</label>
                {{form.email|as_crispy_field }}
              </div>
              <div class="form-group m-b-10">
                <label class="col-form-label">Password</label>
                <div class="form-input position-relative">
                  {{ form.password1|as_crispy_field }}
                 
                </div>
              </div>
              <div class="form-group m-b-10">
                <label class="col-form-label">Confirm Password</label>
                <div class="form-input position-relative">
                  {{ form.password2|as_crispy_field }}
                 
                </div>
              </div>
              <div class="form-group mb-0">
                <div class="checkbox p-0">
                  {{form.term}}
                  <label class="text-muted" for="term_cond"
                    >Agree with privacy policy</label
                  >
                </div>
                <input
                 class="btn btn-primary w-100 bg-primary" 
                 type="submit" name="patient" value="Register"/> 

              </div>
              <p class="mt-4 mb-1">
                Already have an account?<a
                  class="ms-2 text-primary"
                  href="{% url 'accounts:login' %}"
                  >Sign in</a
                >
              </p>
              <a
                class="ms-1 text-primary"
                href="{%url 'accounts:doctor-register' %}"
                >Register as doctor?</a
              >
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- JQuery v3.5.1 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- popper js -->
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>

    <!-- Main Custom JQuery -->
    <script src="{% static 'js/toggleFullScreen.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    {% endblock %}
  </body>
</html>